name: Latest blog post workflow
on:
  schedule:
    # Runs every 6 hours at minute 5
    - cron: '5 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts from personal website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG"
          accept_header: "*/*"
          feed_list: "https://ajmaradiaga.com/feed.xml"
