name: Latest SAP Community blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '13 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest SAP Community blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "SAP-COMMUNITY"
          user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
          feed_list: "https://content.services.sap.com/feed?author=ajmaradiaga&title=All%20content%20by%20Antonio%20Maradiaga"